pipeline {
    agent any

    environment {
        XCODE_SCHEME = 'AnimationDemo'
        XCODE_WORKSPACE = 'AnimationDemo.xcworkspace'
    }

    stages {
        stage('Build') {
            steps {
                script {
                    sh "xcodebuild -workspace ${AnimationDemo.xcworkspace} -scheme ${AnimationDemo} clean build"
                }
            }
        }



    post {
        always {
            // Cleanup steps or notifications
        }
    }
}